### ISSUE TITLE
Add ability to merge config-trees

### ISSUE THREAD

**Issue by kolstae** [gurkankaymak/hocon#1]
One of the really powerful features of lightbends library is [merging config-trees](https://github.com/lightbend/config#merging-config-trees). It would be really great to have this in go as well.

**Comment by gurkankaymak** [comment]
sure, thanks for the feedback

**Comment by kolstae** [comment]
That was fast :)
Would it be better to create a new object for the merged config? So fallback isn't changed.

**Comment by gurkankaymak** [comment]
good point 👍
