### ISSUE TITLE
use "#" comment has an error

### ISSUE THREAD

**Issue by Arrnitage** [gurkankaymak/hocon#12]
When has two lines comment , like 
```
# first line
# second line
```
then , it has an error 
<img width="617" alt="image" src="https://user-images.githubusercontent.com/48816467/153182261-28555f80-7d86-4d0e-8aa2-ab95d9f93342.png">

**Comment by srgg** [comment]
Have the same issue parsing steampipe plugin connection config:

```
connection "aws" {	
				plugin    = "aws@0.34"
				secret = "345"
				# key = "456"
			}
```

**Comment by gurkankaymak** [comment]
both cases are fixed
