### ISSUE TITLE
double characters " rerurn element in arrays of string

### ISSUE THREAD

**Issue by MaratGGG** [gurkankaymak/hocon#21]
Array string returns elements with double characters "
example (v1.2.7):
      brokers: ["127.0.0.1:8080"] => brokers[1] ""127.0.0.1:8080""
previously (v1.2.6):
      brokers: ["127.0.0.1:8080"] => brokers[1] "127.0.0.1:8080"

**Comment by Rory-Z** [comment]
Hi, @MaratGGG return character " because the "127.0.0.1:8080" has `:`, please see this PR: https://github.com/gurkankaymak/hocon/pull/19
