### ISSUE TITLE
Another comment oddity

### ISSUE THREAD

**Issue by pgalbavy-itrs** [gurkankaymak/hocon#26]
Thanks for the rapid fix of #25 

I am trying to support in-the-field config files, so I have to test against messy files.

In this case:

```hocon
"key": {
    "name": value
    # comment on it's own line - this is OK
    "name2": value
    # comment on it's own line - remove this and it works
    "name3": {
        "another": value
    }
}
```

generates:

```bash
$ ./play 
panic: invalid config object! at: 9:1, invalid token }

goroutine 1 [running]:
main.main()
        /home/peter/play/main.go:39 +0x7e5
```

removing the second comment - when it precedes a `{ ... }` fixes it.

**Comment by gurkankaymak** [comment]
thanks for reporting, the problem was with the `'` character, if a line contains it the golang parser appends newline (`\n`) to the latest token instead of a separate token, in that case the next line is also consumed as comment

**Comment by pgalbavy-itrs** [comment]
Again, thanks for the rapid fix, but found yet another one. I can share our full default config file if it helps?

```hocon
key: {
    # //
    name: {
        name: value
    }
}
```

Any URL in a comment before a { ... } encodes object causes an error - I will assume it's the '//' being seen as a comment as well and getting something out of sync. I have not checked what happens for /* ... */ inside # or // prefixed single lines, but I am guessing it's going to have similar issues...

**Comment by pgalbavy-itrs** [comment]
Yep, this also fails:

```hocon
key: {
    # /* this is not ok */
    name: {
        name: value
    }
}
```
