### ISSUE TITLE
Unable to use the .(dot) or some valid characters in a String in the array

### ISSUE THREAD

**Issue by floating-cat** [gurkankaymak/hocon#33]
example:

```
url = example.com // this works
urls = [
  example.com  // this not works
]
```

errors:

```
error: missing comma! at: 3:10, values should have comma or ASCII newline ('\n') between them
```

In https://hocon-playground.avelier.dev/, this can be recognized correctly:

![image](https://user-images.githubusercontent.com/6748077/208063852-f991759b-8ed8-4cf5-b014-f1c11067d77e.png)

**Comment by sholsapp** [comment]
I'm impacted by this as well. Any pointers on fixing this?

**Comment by sholsapp** [comment]
Is there any workaround I can apply to this issue, like quoting my strings in the HOCON source?

**Comment by gurkankaymak** [comment]
hi @sholsapp fixed the issue, to answer your workaround question for future reference, issues related to unquoted strings always works properly if you define your values as strings (surrounding with double quotes) instead of unquoted

**Comment by sholsapp** [comment]
Thanks @gurkankaymak I really appreciate it.

I still see the error on lines like this, that contain substitutions. To be honest, I can't tell what the authors initial intent here was, nor if this is 

```
x.y = "foo"
a.b = "baz"

arr = [
          ${x.y}"."${a.b}
]
```

Is this the same issue, or a different one?

![image](https://user-images.githubusercontent.com/969813/208497850-9e6537c8-812a-4300-af6c-fc9d6ff6a8b1.png)

**Comment by floating-cat** [comment]
@gurkankaymak Thanks for your quick fix!
@sholsapp From my testing, the latest version of this library still can't parse your conf. Unfortunately, I don't see any workaround for your case. You could also create a new issue for tracking this parsing problem. Thanks.

**Comment by sholsapp** [comment]
Okay, I'll create a new issue shortly. Hopefully it's an easy fix. Would love to use this library. 😄

**Comment by sholsapp** [comment]
Filed https://github.com/gurkankaymak/hocon/issues/34
